
name: CI

on:
  push:
    branches: [ "main" ] 

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: echo "¡Hola, mundo! Este es un mensaje de prueba."
    